### ISSUE TITLE
Add debug parameter for git-sync deployment to chart values

### ISSUE THREAD

**Issue by oxr463** [rancher/git-mirror#21]
We'll need to add this to the deployment template:

```
spec:
  containers:
    - args:
      - -v 9
      command:
      - /git-sync
```

Reference(s):
- https://github.com/kubernetes/git-sync#primary-flags
