### ISSUE TITLE
Replace git-sync with CronJob

### ISSUE THREAD

**Issue by oxr463** [rancher/git-mirror#23]
After finally getting git-sync to play nicely with git-porter, I realized that it is not actually setup for use on the server-side... It's basically just doing a shallow clone, but we need a `--bare` clone and then synchronization on top of that.

Reference(s):
- https://git-scm.com/book/en/v2/Git-on-the-Server-Getting-Git-on-a-Server
- https://github.com/influxdata/helm-charts/blob/master/charts/influxdb/templates/backup-retention-cronjob.yaml
- https://github.com/kubernetes/git-sync/issues/184

**Comment by oxr463** [comment]
We'll need two more containers:
- init container for the `git clone --mirror`
- cronjob container for `git fetch && git push`

The `git push` will need to push to the git-porter instance.

**Comment by oxr463** [comment]
```
apiVersion: batch/v1
kind: CronJob
metadata:
  name: git-mirror
  namespace: git-mirror-chart-testing
spec:
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 1
  jobTemplate:
    metadata:
      creationTimestamp: null
    spec:
      template:
        metadata:
          creationTimestamp: null
        spec:
          affinity: {}
          containers:
          - args:
            - -c
            - echo ${GIT_REPOSITORY}
            command:
            - /bin/sh
            env:
            - name: GIT_REPOSITORY
              value: https://github.com/rancher/rke2-charts
            image: alpine:latest
            imagePullPolicy: Always
            name: git-mirror
            resources: {}
            terminationMessagePath: /dev/termination-log
            terminationMessagePolicy: File
            workingDir: /tmp/git
          dnsPolicy: ClusterFirst
          restartPolicy: Never
          schedulerName: default-scheduler
          securityContext: {}
          serviceAccount: default
          serviceAccountName: default
          terminationGracePeriodSeconds: 30
  schedule: '* * * * *'
  successfulJobsHistoryLimit: 3
  suspend: false
```
